name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ou toute autre branche que tu utilises

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion Ã  Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build de l'image Docker
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      # Push de l'image sur Docker Hub
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
