name: CI - Build Docker & Update Argo Manifests

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupérer le code Flask
    - name: Checkout Flask repo
      uses: actions/checkout@v4

    # 2️⃣ Login Docker Hub (username + token)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 3️⃣ Build + tag + push image Docker
    - name: Build and Push Docker image
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} \
          -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    # 4️⃣ Cloner le repo Kubernetes (Argo CD)
    - name: Clone Kubernetes manifests repo
      run: |
        git clone https://github.com/Brisous/deploy_imageDocker.git

    # 5️⃣ Mettre à jour le tag de l’image
    - name: Update image tag in deployment.yaml
      run: |
        cd deploy_imageDocker
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}|" deployment.yaml

    # 6️⃣ Commit & push vers le repo manifests
    - name: Commit and push manifests
      run: |
        cd deploy_imageDocker
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
